# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments

# Site settings
title: "zachmoshe.com"
quote: "Computers are useless. They can only give you answers."
quote_by: "Pablo Picasso, 1960s"
quote_reference: "http://en.wikiquote.org/wiki/Pablo_Picasso#1960s"
description: >
    All about data, data mining and new technologies 

email: zachmoshe@gmail.com
#blog logo
logo: "/assets/images/author.jpg"
corner_logo: "/assets/images/zm_logo.jpg"
# blog cover
cover: "/assets/images/blog_cover.jpg"

# name: 'Zach Moshe'
author: 'Zach Moshe'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://zachmoshe.com"
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/zachmoshe
    desc: Follow me on twitter
    # share_url: http://twitter.com/share
    # share_title: ?text=
    # share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/zach.moshe
    desc: Connect with me on facebook
    # share_url: //www.facebook.com/sharer.php
    # share_title: ?t=
    # share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/zachmoshe
    desc:	Fork me on github
    # share_url:
    # share_title:
    # share_link:

  - icon: linkedin
    url: https://www.linkedin.com/in/zachmoshe
    desc: Connect with me on linkedin
    # share_url: http://www.linkedin.com/shareArticle?mini=true
    # share_title: "&title="
    # share_link: "&url="

  - icon: stack-overflow
    url: http://stackoverflow.com/users/1643257/zach-moshe
    desc: Connect with me on stackoverflow

